---
title: 'Step 3: Bioeconomic model'
author: "Seleni Cruz"
date: "April 28, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r prepare data}
mrate <- read.csv(here::here("raw_data", "mrate.csv"))
#variables from CMSY2
pts <- read.csv(here::here("inputs","ref_pts.csv"))%>%
  merge(mrate, by="Name")%>%
  select(Name, Adjusted, r, r.low, r.hi, k, k.low, k.hi, f, f_lo, f_hi, b, b_lo, b_hi, m.rate, 
         msy, msy.low, msy.hi, bmsy, bmsy.low, bmsy.hi, fmsy, fmsy_lo, fmsy_hi)

#2018 prices
price <- read.csv(here::here("raw_data", "MarketPrice.csv"))

#open access equilibrium at 30%
data.0.3 <- merge(pts, price, by="Name")%>%
  mutate (f_bar = 2 * (1- 0.3/2),
          c = (p * f_bar * 0.3 *msy)/(fmsy * f_bar), 
          c.lo = (p.lo * f_bar * 0.3 *msy.low)/(fmsy_lo * f_bar), 
          c.hi = (p.hi * f_bar * 0.3 *msy.hi)/(fmsy_hi * f_bar), 
          profit.msy = p * msy - (c* fmsy), 
          profit.msy.lo = p.lo * msy.low - (c.lo * fmsy_lo),
          profit.msy.hi = p.hi * msy.hi - (c.hi * fmsy_hi))

#MPA Matrix 
MPA.mat <- read.csv(here::here("inputs", "MPA.matrix.csv"))



```

```{r run model}
source(here::here("R", "bioeconomic_model.R"))

t1<-bioeconomic_model(df= data.0.3, years=50, MPA.mat = MPA.mat, start.year = 0)

```

