---
title: "Step2"
author: "Seleni Cruz"
date: "April 28, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages}
library(dplyr)
library(ggplot2)
library(ggrepel)
```

```{r run DLSA function}
catch <- read.csv(here::here("inputs", "catch.csv"))%>%
  filter(Genus=="Atrina" | Genus == "Callinectes"|Genus=="Cephalopholis" | Genus == "Dasyatis"|
           Genus=="Epinephelus" | Genus == "Lutjanus"|Genus=="Micropogonias" | Genus == "Mugil"|
           Genus=="Octopus" | Genus == "Panulirus"|Genus=="Scomberomorus"| Genus=="Squatina")

priors <- read.csv(here::here("inputs", "priors.csv"))

source(here::here("R", "DLSA.R"))

stock_assessment <- stock_assessment(data=catch, priors = priors)

ref_pts<- stock_assessment[[1]]
ref_ts <- stock_assessment[[2]]

write.csv(ref_pts, file.path(here::here("inputs"), "ref_pts.csv"))
write.csv(ref_ts, file.path(here::here("inputs"), "ref_ts.csv"))


ref_pts <- ref_pts%>%
  filter(Adjusted=="MT")

```


```{r}
bmsy<- expression(paste(B/B[MSY]))
fmsy <- expression(paste(F/F[MSY]))

ggplot(ref_pts, aes(x= bbmsy, y=ffmsy))+
  geom_rect(xmin = 0.0, xmax = 1.0, ymin = 0.0, ymax = 1, fill = 'yellow', alpha = 0.1) +
  geom_rect(xmin = 0, xmax = 1, ymin = 1.0, ymax = 7.1, fill = 'red', alpha = 0.1) +
  geom_rect(xmin = 1, xmax = 1.5, ymin = 0, ymax = 1, fill = 'green', alpha = 0.1) +
  geom_rect(xmin = 1, xmax = 2.1, ymin = 1, ymax = 7.1, fill = 'orange', alpha = 0.1)+
  geom_point(aes(size=catch), show.legend = FALSE)+
  scale_size(range = c(2, 8))+
  labs(x=bmsy, y=fmsy)+
  geom_vline(xintercept = 1, linetype="dotted", color="black") +
  geom_hline(yintercept = 1, linetype="dotted", color="black") +
  scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(limits=c(0, 7.1),expand=c(0,0), breaks = c(0, 1, 2, 4, 6), labels= c(0, 1, 2, 4, 6))+
  theme_classic(base_size = 9)+
  geom_text_repel(aes(label = Name, size=4),show.legend=FALSE)

ggsave(here::here("images","Kobe2015_label.jpg"), width=4, height=3, dpi=900)

```

