---
title: "Step 1"
author: "Seleni Cruz"
date: "April 28, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, message=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)

```



##Import and filter CONAPESCA landings dataset by landing sites and fisheries of interest

```{r}
landingsites<- read.csv (here::here("raw_data", "landingsites.csv"))%>%
  filter(Confirmado=="y")

fisheries<-read.csv(here::here("raw_data", "fisheries.csv"), stringsAsFactors = FALSE)

catch<- readRDS (here::here("raw_data", "conapesca.RDS"))%>%
  filter(Estado=="Baja california"| Estado=="Sonora")%>%
  filter(!(NombrePrincipal=="Macarela"|NombrePrincipal=="Sardina"|NombrePrincipal=="Camaron"|NombrePrincipal=="Corvina"
           |NombrePrincipal=="Calamar"|NombrePrincipal=="Anchoveta"))%>%
  tidyr::separate(NombreCientifico,into="Genus", sep=" ", extra='drop', remove=FALSE)%>%
  mutate_at(.vars = "Genus", .funs = gsub, pattern = " spp", replacement = "")%>%
  merge(landingsites, by="SitioDesembarque")%>%
  merge(fisheries, by="Genus")

catch_genus<-catch%>%
  group_by(Genus, Ano)%>%
  summarize(MT=sum(PesoVivo)/1000)%>%
  mutate(MT_20= MT*1.2, MT_40= MT*1.4, MT_60=MT*1.6)%>%
  filter(length(unique(Ano))>5|length(unique(Ano))==5)

write.csv(catch_genus, file.path(here::here("inputs"), "catch.csv"))

value_genus<-catch_genus%>%
  merge(fisheries, by="Genus")%>%
  mutate(Value = MT * Avg2018)

```


#Plotting catch series for each Fishery (Genus)
```{r}

ggplot(catch_genus, aes(x=Ano, y=MT, color=Genus))+
  geom_line(size=1)+
  geom_point()+
  labs(x="Year", y="Yearly total catch catch (MT)", title="Catch series by Genus", subtitle= "2005-2015")+
  theme_classic()+
  scale_x_continuous(limits = c(2005, 2015), expand=c(0,0), breaks= c(2005, 2015), labels = c("2005", "2015"))+
  scale_y_continuous(expand=c(0,0))+
  theme(legend.position = "none")+
  facet_wrap(~Genus, scales = "free", ncol = 7)

ggsave(here::here("images","catch_genus.png"), width = 10, height = 6, dpi=500)

ggplot(catch_genus, aes(x=Ano, y=Value, color=Genus))+
  geom_line(size=1)+
  geom_point()+
  labs(x="Year", y="Value of catch($)", title="Catch series by Genus", subtitle= "2005-2015")+
  theme_classic()+
  scale_x_continuous(limits = c(2005, 2015), expand=c(0,0), breaks= c(2005, 2015), labels = c("2005", "2015"))+
  scale_y_continuous(expand=c(0,0))+
  theme(legend.position = "none")+
  facet_wrap(~Genus, scales = "free", ncol = 7)

 ggsave(here::here("images","catch_value.png"), width = 10, height = 6, dpi=500)


```


